# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            veganised.co.uk
tagline:          The vegan interpretation
url:              http://veganised.co.uk
paginate:         1
baseurl:          /
author:
  name:           Martin Stolz
  url:            https://twitter.com/martin_stolz
  email:          blog@veganised.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Other
excerpt_separator: <!--more-->